### PR TITLE
Bump egui-miniquad to 0.10.0, macroquad to 0.3.15

### PR DESCRIPTION
**Pull request by aleokdev**
Hopefully should fix blending a bit.

### CODE REVIEW

**Comment by aleokdev** [comment]
Apparently macroquad still uses miniquad alpha.45, so this PR can't be merged until it is updated to .46.

**Comment by optozorax** [comment]
Thank for the PR!

> Apparently macroquad still uses miniquad alpha.45, so this PR can't be merged until it is updated to .46.

You can create PR to macroquad repo to speed up the process.

**Comment by aleokdev** [comment]
[Done](https://github.com/not-fl3/macroquad/pull/406); Now we wait :)

**Comment by optozorax** [comment]
I made an issue in the macroquad repo: https://github.com/not-fl3/macroquad/issues/408

**Comment by optozorax** [comment]
New version is here.

**Pull request closed without merging**
